baseurl = "http://john-maxwell.com"
relativeurls = true
languageCode = "en-us"
title = "John's Site"
theme = "hugo-cactus-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[params]
	name = "John Maxwell"
	description = ""
	bio = ""
	# Enter optionally your twitter account
	twitter = "jhnmxwll"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = "Posts"
	copyright = ""
	# Sharing options and author information in posts
	# aboutAuthor = ""
	tweet = ""
	# share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/jhnmxwll"
    #facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/jmmaxwell"
    linkedin = "https://www.linkedin.com/in/maxwelljohnm/"

